---
title: Green FabLab
description: Innovation on the web
email: fabio-alberto.cruz-sanchez@univ-lorraine.fr
menu:
- name: Why innovation
  url: "#innovation"
- name: Network
  url: "#network"
- name: Savoir
  url: "#projects"
- name: Contact
  url: "#contact"
savoir:
- name: Former des managers de l'innovation
  folder: ''
  logo: ''
  link: http://www.ensgsi.univ-lorraine.fr/
  description: Une grande école d'ingénieurs publique
- name: Approfondir les connaissances sur l'innovation
  folder: ''
  logo: ''
  link: https://laboratoire-erpi.wikispaces.com/
  description: Un laboratoire de recherche sur les processus d'innovation, des chaires
    partenariales
- name: Diffuser le <br> concept de   Fab Living Lab
  folder: ''
  logo: ''
  link: http://www.lf2l.fr/
  description: Une plateforme collaborative pour accélerer vos projets
- name: "Évaluer et développer votre capacité à innover"
  folder: ''
  logo: ''
  link: http://innovation-way.com/
  description: Un outil de diagnostic en ligne en 30 minutes
projects:
- name: Participez à un challenge créatif
  folder: ''
  logo: ''
  link: http://48h-innovation-maker.com/ensgsi
  description: Une opération de créativité et d'innovation d'envergure internationale
- name: Rejoignez un projet collaboratif
  folder: ''
  logo: ''
  link: http://linkybymakers.fr/
  description: Découvrez nos ateliers by Makers&copy;
- name: Explorez le Green FabLab
  folder: ''
  logo: ''
  link: http://www.lf2l.fr/Sections/Projets/Green-Fablab/
  description: Conjuguez FabLab et économie circulaire
- name: D'autres projets ou informations &#63;, Contactez-nous!
  folder: ''
  logo: ''
  link: ''
  description: 
